#!/bin/sh

rm ca-key.pem ca.csr ca.pem consul-key.pem consul.csr consul.pem
oc delete statefulset consul
oc delete pvc data-consul-0 data-consul-1 data-consul-2
oc delete svc consul
oc delete secrets consul
oc delete configmaps consul
